### PR TITLE
Remove unused imports

### PR DESCRIPTION
**Pull request by pzygielo**

### CODE REVIEW

**Comment by pzygielo** [comment]
Filed 567788 for 
```
All nodes of label ‘ci-pod-10488367-bad8-486c-a5e0-492617de0f4c’ are offline
```
of [ci/glassfish-copyright-plugin/PR-12/1](https://ci.eclipse.org/glassfish/job/glassfish-copyright-plugin/view/change-requests/job/PR-12/1/console).

**Comment by pzygielo** [comment]
Not sure, but this label is probably generated in this project itself
https://github.com/eclipse-ee4j/glassfish-copyright-plugin/blob/d73b04ca14313ffe24bcd086723fb5165e8e9bf5/Jenkinsfile#L17
Could someone from The GF Team assist in that CI/Jenkins matter, please?

**Comment by fredg02** [comment]
PR https://github.com/eclipse-ee4j/glassfish-copyright-plugin/pull/13 needs to be merged first.

**Comment by pzygielo** [comment]
@fredg02 - thank you.

**Review by arjantijms — APPROVED** [review]
LGTM!

**Pull request merged**
